---
apiVersion: v1
kind: Pod
metadata:
  name: test-a 
  namespace: org-1 
  labels:
    run: nginx 
    app: test-a 
spec:
  serviceAccountName: unprivileged
  containers:
    - image: nginxinc/nginx-unprivileged:1.18-perl
      imagePullPolicy: IfNotPresent
      name: nginx
  