apiVersion: v1
kind: Pod
metadata:
  name: pause
  namespace: default
  labels:
    app: pause
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause
      ports:
        - containerPort: 8080